<?php /* @var $payment array, $subscription array, $user array, $logoDataUri string|null, $siteName string */ ?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Subscription Invoice</title>
    <style>
        body { font-family: DejaVu Sans, Arial, Helvetica, sans-serif; font-size: 14px; color: #222; }
        .header { text-align: center; margin-bottom: 24px; }
        .logo { max-height: 60px; margin-bottom: 8px; }
        .title { font-size: 22px; font-weight: bold; margin-bottom: 6px; }
        .meta { font-size: 12px; color: #666; }
        .section { margin-bottom: 18px; }
        .section-title { font-weight: bold; margin-bottom: 8px; }
        table { width: 100%; border-collapse: collapse; }
        th, td { padding: 8px 6px; border: 1px solid #ddd; }
        th { background: #f7f7f7; text-align: left; }
        .amount { font-weight: bold; color: #1a7e1a; }
        .footer { text-align: center; font-size: 12px; color: #888; margin-top: 24px; }
        .status-bar { text-align: right; margin-bottom: 8px; }
        .status-badge { display: inline-block; padding: 6px 14px; border-radius: 999px; font-weight: bold; font-size: 12px; color: #fff; text-transform: uppercase; letter-spacing: 0.3px; }
        .status-paid { background: #198754; }
        .status-pending { background: #fd7e14; }
        .status-failed { background: #dc3545; }
    </style>
</head>
<body>
    <div class="header">
        <?php 
            $ps = strtolower($payment['status'] ?? 'completed');
            $badgeClass = ($ps === 'completed') ? 'status-paid' : (($ps === 'failed') ? 'status-failed' : 'status-pending');
            $badgeText = ($ps === 'completed') ? 'Paid' : (($ps === 'failed') ? 'Failed' : 'Pending');
        ?>
        <div class="status-bar">
            <span class="status-badge <?= $badgeClass ?>"><?= $badgeText ?></span>
        </div>
        <?php if (!empty($logoDataUri)): ?>
            <img class="logo" src="<?= $logoDataUri ?>" alt="Logo">
        <?php endif; ?>
        <div class="title">Subscription Invoice</div>
        <div class="meta">
            Invoice #<?= htmlspecialchars($payment['id']) ?> • Date: <?= isset($payment['created_at']) ? date('M d, Y', strtotime($payment['created_at'])) : date('M d, Y') ?>
        </div>
    </div>

    <div class="section">
        <div class="section-title">Billed To</div>
        <table>
            <tr>
                <th style="width:30%">Name</th>
                <td><?= htmlspecialchars($user['name'] ?? '-') ?></td>
            </tr>
            <tr>
                <th>Email</th>
                <td><?= htmlspecialchars($user['email'] ?? '-') ?></td>
            </tr>
            <tr>
                <th>Role</th>
                <td><?= htmlspecialchars(ucfirst($user['role'] ?? '-')) ?></td>
            </tr>
        </table>
    </div>

    <div class="section">
        <div class="section-title">Subscription Details</div>
        <table>
            <tr>
                <th style="width:30%">Plan</th>
                <td><?= htmlspecialchars($subscription['plan_name'] ?? ($subscription['plan_type'] ?? '-')) ?></td>
            </tr>
            <tr>
                <th>Price</th>
                <td>Ksh<?= number_format((float)($subscription['plan_price'] ?? $payment['amount'] ?? 0), 2) ?></td>
            </tr>
            <?php if (!empty($subscription['current_period_starts_at']) || !empty($subscription['current_period_ends_at'])): ?>
            <tr>
                <th>Period</th>
                <td>
                    <?= !empty($subscription['current_period_starts_at']) ? date('M d, Y', strtotime($subscription['current_period_starts_at'])) : '-' ?>
                    to
                    <?= !empty($subscription['current_period_ends_at']) ? date('M d, Y', strtotime($subscription['current_period_ends_at'])) : '-' ?>
                </td>
            </tr>
            <?php endif; ?>
            <tr>
                <th>Status</th>
                <td><?= htmlspecialchars(ucfirst($payment['status'] ?? 'Completed')) ?></td>
            </tr>
        </table>
    </div>

    <div class="section">
        <div class="section-title">Payment</div>
        <table>
            <tr>
                <th style="width:30%">Amount Paid</th>
                <td class="amount">Ksh<?= number_format((float)($payment['amount'] ?? 0), 2) ?></td>
            </tr>
            <tr>
                <th>Method</th>
                <td><?= htmlspecialchars(ucfirst(str_replace('_', ' ', $payment['payment_method'] ?? '-'))) ?></td>
            </tr>
            <tr>
                <th>Reference</th>
                <td><?= htmlspecialchars($payment['transaction_reference'] ?? '-') ?></td>
            </tr>
        </table>
    </div>

    <div class="footer">
        Generated by <?= htmlspecialchars($siteName ?? 'RentSmart') ?> — <?= date('Y-m-d H:i') ?>
    </div>
</body>
</html>
